// Code generated by "stringer -type=Account"; DO NOT EDIT.

package scaledb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StairsPayment-1]
	_ = x[Loan-2]
	_ = x[Repayment-3]
	_ = x[DuesPayment-4]
	_ = x[Expenditure-5]
	_ = x[Revenue-6]
}

const _Account_name = "StairsPaymentLoanRepaymentDuesPaymentExpenditureRevenue"

var _Account_index = [...]uint8{0, 13, 17, 26, 37, 48, 55}

func (i Account) String() string {
	i -= 1
	if i < 0 || i >= Account(len(_Account_index)-1) {
		return "Account(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Account_name[_Account_index[i]:_Account_index[i+1]]
}
